language: node_js
sudo: false
node_js: [10, 9, 8, 7, 6, 5, 4]
before_script:
  - ./node_modules/.bin/run-rs -q &
  - printf "\n--timeout 10000" >> ./test/mocha.opts
  - ./mongodb-linux-x86_64-3.6.6/bin/mongod --fork --dbpath ./data/db/27017 --syslog --port 27017
  - sleep 2
matrix:
  include:
    - name: "👕Linter"
      node_js: 10
      before_script: skip
      script: npm run lint
notifications:
  email: false
